name: Next.js Shopify CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js with pnpm
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: ./pnpm-lock.yaml
          registry-url: 'https://registry.npmjs.org'
          always-auth: false

      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: pnpm run format:check

  build:
    runs-on: ubuntu-latest

    needs:
      - format-check

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js with pnpm
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
          always-auth: false

      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Lint files
        run: pnpm run lint && pnpm run format

      - name: Build Project
        run: pnpm run build
