# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Next.js Shopify CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./pnpm-lock.yaml

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

  build:
    runs-on: ubuntu-latest
    needs:
      - format-check
      
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x]
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: './package.json'
          cache: ''

      - name: Install dependencies
        run: npm i
        working-directory: ./

      - name: Lint files
        run: npm run lint && npm run format
        working-directory: ./

      - name: Build Project
        run: npm run build
        working-directory: ./
